# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0002_auto_20160306_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellerlogindb',
            fields=[
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mobile', models.BigIntegerField()),
                ('shopname', models.CharField(max_length=80)),
                ('shopid', models.CharField(max_length=80)),
                ('office_no', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=200)),
                ('Address1', models.CharField(max_length=200)),
                ('Address2', models.CharField(max_length=200)),
                ('category', models.BigIntegerField(null=True)),
                ('gcmid', models.CharField(max_length=1000)),
                ('token', models.CharField(max_length=100)),
                ('gps', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='sellerlogin',
        ),
    ]
