# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0005_request_conf_cus_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_conf',
            name='id',
        ),
        migrations.AlterField(
            model_name='request_conf',
            name='Cus_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
