# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0009_request_conf_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_conf',
            name='cus_loc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerlogindb',
            name='sel_loc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
