# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0014_auto_20160330_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_conf',
            name='time',
            field=models.BigIntegerField(default=100),
        ),
    ]
