# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0015_request_conf_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv', models.CharField(max_length=2000, null=True)),
                ('edate', models.CharField(max_length=100)),
                ('sdate', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(max_length=2000, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
