# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0016_adv_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldb',
            name='Sel_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
