# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0017_selldb_sel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldb',
            name='bprice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='selldb',
            name='btime',
            field=models.BigIntegerField(null=True),
        ),
    ]
