# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0021_auto_20160402_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerlogindb',
            fields=[
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mobile', models.BigIntegerField()),
                ('gcmid', models.CharField(max_length=1000)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='selldb',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selldb',
            name='pickup',
            field=models.IntegerField(default=0),
        ),
    ]
