# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0003_auto_20160308_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_link', models.URLField()),
                ('Ser_product', models.CharField(max_length=50)),
                ('Ser_image', models.URLField()),
                ('Ser_price', models.CharField(max_length=50)),
                ('Sel_type', models.BooleanField()),
                ('Sel_comments', models.CharField(max_length=500)),
                ('Cus_expiry', models.IntegerField()),
                ('Cus_id', models.CharField(max_length=30)),
                ('Sel_deltype', models.BooleanField()),
                ('Cus2_conf', models.BooleanField()),
                ('Sel2_conf', models.BooleanField()),
            ],
        ),
    ]
