# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0004_request_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_conf',
            name='cus_category',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
