# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0006_auto_20160310_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_conf',
            name='Cus2_conf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request_conf',
            name='Cus_expiry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request_conf',
            name='Sel2_conf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request_conf',
            name='Sel_deltype',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request_conf',
            name='Sel_type',
            field=models.BooleanField(default=False),
        ),
    ]
