# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0011_auto_20160312_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlogindb',
            name='imagepath',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
